# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-27 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20160827_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='model_pic',
            field=models.ImageField(default='blog/images/already.png', upload_to=''),
        ),
    ]
