# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-27 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20160827_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='model_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
